[tool.bumpversion]
current_version = "0.8.0"
commit = true
message = "chore: bump version to {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"
setup_hooks = [
  "mise run update-changelogs -- --commit",
]

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
glob = "packs/*/CHANGELOG.md"
search = "## Unreleased"
replace = "## v{new_version} - {now:%Y-%m-%d}"
ignore_missing_version = true

[[tool.bumpversion.files]]
glob = "packs/*/metadata.hcl"
