[tool.bumpversion]
current_version = "0.0.1"
commit = true
message = "chore: bump version to {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"
setup_hooks = [
  "mise run update-changelogs",
  "git add -- '*/CHANGELOG.md'",
]

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
glob = "packs/*/CHANGELOG.md"
search = "## Unreleased"
replace = """
## Unreleased

## v{new_version} - {now:%Y-%m-%d}"""

[[tool.bumpversion.files]]
glob = "packs/*/metadata.hcl"
